##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  rabbitmq:
    addresses: 192.168.2.108
    port: 5672
    username: admin
    password: admin123
    virtual-host: testV
    #确认消息配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1       #redis服务器地址
    port: 6379            #redis服务器端口
    password: admin123    #redis 密码
    database: 1           #默认连接的库
    timeout: 2000ms         #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 3000        # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 3000          # 连接池中的最大空闲连接
        min-idle: 0             # 连接池中的最小空闲连接
        #        max-wait: -1            # 连接池最大阻塞等待时间（使用负值表示没有限制）
        time-between-eviction-runs: 60000ms  #空闲链接检测线程检测周期。如果为负值，表示不运行检测线程。（单位：毫秒，默认为-layer）
  ###################  mongodb配置  ###################
  data:
    mongodb:
      host: 192.168.2.83
      port: 27017
      database: log4j
  ###################  mysql配置  ###################
  datasource:
    dynamic:
      primary: master       #设置默认的数据源或者数据源组,默认值即为master
      strict: false         #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/docbase_entry?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
          username: root
          password: 20030101x
          db-name: docbase_entry    # 主数据与需要配置db-name
          driver-class-name: com.mysql.cj.jdbc.Driver
docbase:
  es-address: 127.0.0.1
  es-port: 9200
  es-base: docbase-produce-ik
  username: elastic
  password: 123456
  file.validate.type: pdf,docx,doc,xlsx,xls,ppt,pptx,txt,jpg,png,gif,ceb,exe,mp3,mp4
  filedir: C://knowledge/file/
  fileByKey: C://knowledge/fileByKey/
  pdfFile: C://knowledge/pdfFile/
  pdfFileByKey: C://knowledge/pdfFileByKey/
  downloadFile: C://knowledge/downloadFile/
  downloadPdfFile: C://knowledge/downloadPdfFile/
  downloadFileByKey: C://knowledge/downloadFileByKey/
  downloadPdfFileByKey: C://knowledge/downloadPdfFileByKey/
  videoDir: C://knowledge/videoDir/
  editSavePath: C://knowledge/yozoedit/
  ThumbnailsDir: C://knowledge/ThumbnailsDir/
  breakdir: C://knowledge/breaktmp/
  editdir: C://
  uploadPath: C://knowledge/uploads
  zipDownloadPath: C://knowledge/uploads//zip
  picCommond: true
  officeHomeDir:  C://Program Files//LibreOffice
  ffmpegDir: D:\桌面\项目实训\ffmpeg\ffmpeg-4.3-win64-static\bin\ffmpeg.exe
  mydic: D:\installs\develop\codeprograms\workplace_idea\DW\dw-main\src\main\webapp\static\
  isRole: false

fastdfs:
  #是否启用fastdfs
  using: false

###################  审核系统配置  ###################
examine:
  #是否启用审核系统
  using: false
company:
  using: true
isProject:
  using: true
###################  审核系统配置  ###################
SPACE:
  SIZE: 1024.0
  #单位MB

################### 在线编辑配置 开始 ##################
onlineEdit:
  using: false                                 #是否启用在线编辑
  validTime: 3600                            #链接有效时间，单位秒
  serverNum: 2                               #应用服务节点数目，集群部署使用
  serverAddress_0: http://192.168.2.125:80  #应用服务节点0地址
  serverAddress_1: http://192.168.2.152:80  #应用服务节点1地址
  licenseServer: http://localhost:8085      #在线编辑文件服务授权服务地址
  localServer: http://192.168.14.65:8080     #本机服务地址（废弃）
  yozoServer: http://192.168.2.145:8080      #永中服务地址（废弃）
################### 在线编辑配置 结束 ##################

################### 上传项目使用手册地址配置 开始 ##################
handBook:
  addressList: 127.0.0.1:8083
################### 上传项目使用手册地址配置 结束 ##################