##########################################################
###################  测试环境的profile  ###################
##########################################################

spring:
  profiles: test
  cache:
    type: redis
  redis:
    host: 127.0.0.1       #redis服务器地址
    port: 6379            #redis服务器端口
    password: admin123    #redis 密码
    database: 1           #默认连接的库
    timeout: 2000ms         #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 3000        # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 3000          # 连接池中的最大空闲连接
        min-idle: 0             # 连接池中的最小空闲连接
        max-wait: -1            # 连接池最大阻塞等待时间（使用负值表示没有限制）
        time-between-eviction-runs: 60000ms  #空闲链接检测线程检测周期。如果为负值，表示不运行检测线程。（单位：毫秒，默认为-layer）
###################  mongodb配置  ###################
  data:
    mongodb:
      host: 192.168.2.83
      port: 27017
      database: log4j
###################  mysql配置  ###################
  datasource:
    url: jdbc:mysql://192.168.2.145:3306/docbase-test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    db-name: docbase-jxdmain-test
    filters: log4j,mergeStat
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 5
docbase:
  es-address: 192.168.2.145
  es-port: 9200
  es-base: docbasenew
  username: elastic
  password: 123456
  file.validate.type: pdf,docx,doc,xlsx,xls,ppt,pptx,txt,jpg,png,gif,ceb,exe,mp3,mp4
  filedir: /opt/file/                                                 #上传文件目录
  fileByKey: /opt/fileByKey/                                           #上传的文件转化为加密文件的目录
  pdfFile: /opt/pdfFile/                                               #上传的PDF文件目录
  pdfFileByKey: /opt/pdfFileByKey/                                    #上传的pdf加密后的目录
  downloadFile: /opt/downloadFile/                                    #下载的文件解密后目录
  downloadPdfFile: /opt/downloadPdfFile/                              #预览的文件解密后目录
  downloadFileByKey: /opt/downloadFileByKey/                          #下载的文件解密前目录
  downloadPdfFileByKey: /opt/downloadPdfFileByKey/                    #预览的文件解密前目录
  editSavePath: /opt/yozoedit/
  ThumbnailsDir: /opt/ThumbnailsDir/                                    #图片缩略图目录
  breakdir: /opt/breaktmp/                                                #文件分片目录
  editdir: /opt                                                                  #在线编辑目录
  uploadPath: /opt/knowledge/uploads
  zipDownloadPath: /opt/knowledge/uploads//zip
  picCommond: true
  officeHomeDir: /opt/libreoffice6.4
  ffmpegDir: /usr/local/ffmpeg/ffmpeg-git-20200722-amd64-static/ffmpeg
  videoDir: /opt/videoDir/
  waterPrint: 金现代
  mydic: F:\DW\DW\dw-main\src\main\webapp\static\
  isRole: true
fastdfs:
  #是否启用fastdfs
  using: true
examine:
    #是否启用审核系统
    using: false
company:
  using: true
isProject:
  using: false
SPACE:
  SIZE: 1024.0    #单位MB


################### 永中在线编辑配置 开始 ##################
onlineEdit:
  using: true                                 #是否启用在线编辑
  validTime: 3600                            #链接有效时间，单位秒
  serverNum: 1                               #应用服务节点数目，集群部署使用
  serverAddress_0: http://192.168.2.145:8089  #应用服务节点0地址
  licenseServer: http://localhost:8085      #在线编辑文件服务授权服务地址
  localServer: http://192.168.14.65:8080     #本机服务地址（废弃）
  yozoServer: http://192.168.2.145:8080      #永中服务地址（废弃）